### ISSUE TITLE
Need help with syntax

### ISSUE THREAD

**Issue by Slj4Gray** [faveoled/appimage2deb#1]
I am a total beginner with linux and am having trouble with using Appimage2deb. it keeps saying unknown option and giving me a letter. i have no idea what it means. Some proper documentation would be a good idea.

**Comment by faveoled** [comment]
Post your full command

**Comment by faveoled** [comment]
Docs are in `appimage2deb -h`

**Comment by Slj4Gray** [comment]
appimage2deb -home/steve/downloads/Superslicer-ubuntu_18.04-2.5.59.8

**Comment by faveoled** [comment]
1. /home instead of -home
2. downloads should probably start with a capital letter
3. .AppImage likely missing at the end

**Comment by Slj4Gray** [comment]
Now i'm getting
Execution failed. Error details: File not found: /home/steve/Downloads/Superslicer-ubuntu_18.04-2.5.59.8.Appimage

**Comment by faveoled** [comment]
Some other casing error (App**I**mage maybe)

**Comment by Slj4Gray** [comment]
Found the problem.
appimage2deb /home/steve/Downloads/SuperSlicer-ubuntu_18.04-2.5.59.8.AppImage worked
Thanks for your help.
